# Generated by Django 5.2.1 on 2025-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, verbose_name='نوع')),
                ('base_weight', models.FloatField(blank=True, null=True, verbose_name='وزن پایه')),
                ('waste', models.FloatField(blank=True, null=True, verbose_name='دور ریز')),
                ('net_weight', models.FloatField(blank=True, null=True, verbose_name='وزن خالص')),
                ('base_price', models.FloatField(blank=True, null=True, verbose_name='قیمت محصول بر پایه وزن پایه')),
                ('real_price', models.FloatField(blank=True, null=True, verbose_name='قیمت حقیقی')),
            ],
        ),
    ]
