# Generated by Django 5.2.1 on 2025-05-10 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع محصول')),
                ('base_weight', models.FloatField(verbose_name='وزن پایه')),
                ('waste', models.FloatField(verbose_name='دور ریز')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight', models.FloatField(default=1000, verbose_name='وزن کل (گرم)')),
                ('price_per_kilo', models.FloatField(default=10000, verbose_name='قیمت هر کیلو')),
                ('waste_weight', models.FloatField(blank=True, null=True, verbose_name='وزن دور ریز')),
                ('net_weight', models.FloatField(blank=True, null=True, verbose_name='وزن خالص')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='قیمت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producttype', verbose_name='نوع محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
