# Generated by Django 5.2.1 on 2025-05-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_weight', models.FloatField(blank=True, null=True, verbose_name='وزن خالص')),
                ('base_price', models.FloatField(verbose_name='قیمت محصول بر پایه وزن پایه')),
                ('real_price', models.FloatField(blank=True, null=True, verbose_name='قیمت حقیقی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع محصول')),
                ('base_weight', models.FloatField(verbose_name='وزن پایه')),
                ('waste', models.FloatField(verbose_name='دور ریز')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصولات',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='productinstance',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producttype', verbose_name='نوع محصول'),
        ),
    ]
