# Generated by Django 5.2.1 on 2025-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productinstance_producttype_delete_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='real_price',
        ),
        migrations.AddField(
            model_name='productinstance',
            name='price_per_kilo',
            field=models.FloatField(default=10000, verbose_name='قیمت هر کیلو'),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='total_weight',
            field=models.FloatField(default=1000, verbose_name='وزن کل (گرم)'),
        ),
        migrations.AddField(
            model_name='productinstance',
            name='waste_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن دور ریز'),
        ),
    ]
